server:
  port: 8081
spring:
  datasource:
    username: ${MYSQL_USER:<user>}
    password: ${MYSQL_PASSWORD:<password>}
    url: jdbc:mysql://${MYSQL_HOST:<host>}:${MYSQL_PORT:<port>}/<db>
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
